// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


console.log("hi");

var myTree = /* Node */{
  _0: /* Node */{
    _0: /* Leaf */0,
    _1: 1,
    _2: /* Leaf */0
  },
  _1: 2,
  _2: /* Node */{
    _0: /* Leaf */0,
    _1: 3,
    _2: /* Leaf */0
  }
};

exports.myTree = myTree;
/*  Not a pure module */
