// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Set from "functional-data-structure/src/datatype/set.bs.js";
import * as Tree from "functional-data-structure/src/datatype/tree.bs.js";

var myArray = [
  1,
  2,
  3,
  4,
  5
];

var mySet = $$Set.$$Set.make(myArray);

console.log(mySet);

var tr = /* Node */{
  _0: /* Leaf */0,
  _1: 5,
  _2: /* Leaf */0
};

console.log(Tree.Tree.to_list(tr));

console.log("123");

export {
  myArray ,
  mySet ,
  tr ,
}
/* mySet Not a pure module */
