// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_array = require("rescript/lib/js/js_array.js");

function displayDiscount(discount) {
  if (typeof discount === "number") {
    return "No Discount";
  } else if (discount.TAG === /* PercentDiscount */0) {
    return "Percent Discount: " + (discount._0 * 100.0).toString() + "%";
  } else {
    return "Fixed Discount: " + discount._0.toString();
  }
}

var discounts = [
  {
    TAG: /* PercentDiscount */0,
    _0: 0.10
  },
  {
    TAG: /* FixedDiscount */1,
    _0: 20
  },
  /* NoDiscount */0
];

var htmlDiscounts = Js_array.map(displayDiscount, discounts);

console.log(htmlDiscounts);

exports.displayDiscount = displayDiscount;
exports.discounts = discounts;
exports.htmlDiscounts = htmlDiscounts;
/* htmlDiscounts Not a pure module */
