// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_array from "rescript/lib/es6/js_array.js";

function displayDiscount(discount) {
  if (typeof discount === "number") {
    return "<code>No Discount</code>";
  } else if (discount.TAG === /* PercentDiscount */0) {
    return "Percent Discount: " + (discount._0 * 100.0).toString() + "%";
  } else {
    return "Fixed Discount: " + discount._0.toString();
  }
}

var discounts = [
  {
    TAG: /* PercentDiscount */0,
    _0: 0.10
  },
  {
    TAG: /* FixedDiscount */1,
    _0: 20
  },
  /* NoDiscount */0
];

function htmlDiscounts(param) {
  return Js_array.map(displayDiscount, discounts);
}

console.log(htmlDiscounts);

export {
  displayDiscount ,
  discounts ,
  htmlDiscounts ,
}
/*  Not a pure module */
